### ISSUE TITLE
Is this Repo active?

### ISSUE THREAD

**Issue by jjacobson95** [prakashsvmx/minio-js-react-18-build#1]
I'm currently looking for support with creating a react JS button that can upload a file to minio. Is this a possibility?

I've cloned and tested this repo and it doesn't seem to create new or list active buckets.

**Comment by prakashsvmx** [comment]
@jjacobson95  this has been updated with examples of upload, list , delete ( not fully tested)

**Comment by prakashsvmx** [comment]
e.g: https://github.com/prakashsvmx/minio-js-react-18-build/blob/main/src/cmp/UploadFile.js

**Comment by prakashsvmx** [comment]
Example added
List Buckets
List Objects in Bucket/Prefix
Delete Object.
